name: Docker Image CI

on:
  workflow_dispatch: #for dispatch
  push:
    branches: 
      - 'feature-githubaction-test'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
   
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
   
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./centos/Dockerfile
        push: true
        tags: hypersql-pg14:centos
        #secrets: |
         #GIT_AUTH_TOKEN=${{secrets.GITGUB_TOKEN}}
